# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: websiteCI

#on:
#  push:
#    branches: [ "master" ]
  # 当有 push 操作到主分支时触发（PR 合并后）
on:
  workflow_dispatch:
    inputs:
      manual-run:
        description: '手动运行工作流'
        required: true
        default: 'true'
        
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Run genarate
      uses: borales/actions-yarn@v4
      with:
        cmd: website-generate
    - name: Collect Artifact
      uses: actions/upload-artifact@v4
      with:
        name: website-ssg
        path: website/dist
  # notify:
  #   runs-on: ubuntu-latest
  #   needs: [build]  
  #   steps:  
  #   # 不论前面的 job 成功或失败都会执行
  #     - name: Notify
  #       run: |
  #         cat ${{ needs.build. }}
      # - name: Notify via Feishu
      #   if: success() || failure()
      #   run: |
      #     curl -X POST "$FEISHU_WEBHOOK_URL" \
      #       -H 'Content-Type: application/json' \
      #       -d '{
      #       "msg_type": "text",
      #       "content": {
      #         "text": "CI/CD Job Status: \nWebsite Job: ${{ needs.artifact.result }} \nUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCommit: ${{ github.sha }}"
      #       }
      # #     }'
      #   env:
      #     FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
